version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_storage_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=chat_app_development
      - MYSQL_USER=user
    volumes:
      - databse_storage_data:/var/lib/mysql
    ports:
      - "3307:3306"

  rails:
    build: .
    command: bash -c "rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    depends_on:
      - db
      - elasticsearch
    environment:
      - MYSQL_DATABASE=chat_app_development
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - ELASTIC_HOST=elasticsearch
    links:
      - db
      - elasticsearch
    ports:
      - "3000:3000"

volumes:
  elasticsearch_storage_data: {}
  databse_storage_data: {}
